### ISSUE TITLE
Weyl tensor

### ISSUE THREAD

**Issue by draleth** [bshoshany/OGRe#1]
Can you add the Weyl tensor to this package?

**Comment by draleth** [comment]
My code for Weyl tensor in FLRW metric

TList@TCalc["Weyl2FLRW", 
  "FLRWRiemann"["\[Rho]\[Sigma]\[Mu]\[Nu]"] + 
   1/2 (("FLRWRicciTensor"["\[Rho]\[Nu]"] . 
        "FLRW"["\[Sigma]\[Mu]"]) - ("FLRWRicciTensor"["\[Rho]\[Mu]"] .
         "FLRW"["\[Sigma]\[Nu]"]) + ("FLRWRicciTensor"[
         "\[Sigma]\[Mu]"] . 
        "FLRW"["\[Rho]\[Nu]"]) - ("FLRWRicciTensor"["\[Sigma]\[Nu]"] .
         "FLRW"["\[Rho]\[Mu]"])) + 
   1/6 ("FLRWRicciScalar"[
       ""] . ("FLRW"["\[Rho]\[Mu]"] . "FLRW"["\[Sigma]\[Nu]"] - 
        "FLRW"["\[Rho]\[Nu]"] . "FLRW"["\[Sigma]\[Mu]"]))]

**Comment by bshoshany** [comment]
Thanks for the suggestion! This is already on my TODO list (and easy to implement), but will have to wait until the next release, which will take a few months since I'm currently on hiatus from software development due to heavy teaching load.

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released, and has a new module, `TWeyl[]`, for calculating the Weyl tensor! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
