### ISSUE TITLE
Greek letter are huge

### ISSUE THREAD

**Issue by NailGit** [bshoshany/OGRe#11]
Hi, 
I installed new version of Mathematica 14.1 and outout has Latin and Greek. The Greek letters are huge, see below. 
What I have to do against this behavior? 
![greek](https://github.com/user-attachments/assets/12387b78-93a9-4055-a688-313e9ce721cf)

**Comment by NailGit** [comment]
Sorry, I found the reason. I use my own stylesheet. Changing to standard report style, output is normal.

**Comment by bshoshany** [comment]
Glad to hear that you managed to resolve this issue!

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
