### ISSUE TITLE
Output -> Latex

### ISSUE THREAD

**Issue by NailGit** [bshoshany/OGRe#3]
By default, the output of the calculation is in the `DisplayFormula` style. The copy-paste as Latex format in this style is very strange. For example, the copying of component of tensor Riemann R^t_{tutu} (in Mathematica notebook looks very beautiful) gives \text{R}_{\text{t}\text{u}\text{t}\text{u}}^{\text{t}\text{u}\text{t}\text{u}} in the latex file, which is wrang. You wrote in the documentation that it is possible to change output by using Edit StyleSheet. I tried but unsuccessfully. Maybe better to make some operator like TSetOutput by using which one could change style at the beginning? I tried to change DisplayFormula to Output inside of your OGRe.m file. The output changed but the same problem of copy-paste to Latex.

**Comment by bshoshany** [comment]
Thank you for the suggestion. The style of a cell only controls how the contents of the cell are presented in Mathematica: font size, color, and so on. The contents of the cell are independent of the style. So changing the style won't change the TeX code you get from the cell.

The reason you get the same indices on both the top and the bottom is that OGRe actually prints all the indices, but makes some of them invisible, to ensure proper spacing. In a future release I will include a module name `TTeX[]`(or something similar) that will output the correct TeX code for a tensor.

Hope this helps!

**Comment by NailGit** [comment]
Thank you. It will be the best solution.

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released, and has two new modules, `TTeXShow[]` and `TTeXList[]`, for getting the TeX code directly! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
