### ISSUE TITLE
Something wrong When I calc the Weyl Tensor

### ISSUE THREAD

**Issue by Jayce-Ping** [bshoshany/OGRe#7]
# Problem

I want to use the definition of Weyl Tensor:
$C_{abcd}=R_{abcd}-\frac{1}{n-2}(g_{ac}R_{db}-g_{ad}R_{cb}-g_{bc}R_{da}+g_{bd}R_{ca})+\frac{1}{(n-1)(n-2)}R(g_{ac}g_{db}-g_{ad}g_{db})$
to calculate the Weyl Tensor. But the result includes something like “( )”, which is a couple of parentheses within nothing.

And I used **TGetComponents** to get the component of the result, and test its symmetry with **TensorSymmetry**. The result is not correspond to the Weyl Tensor's symmetry. I think there is something wrong. 

# More tries

Besides, inspired by your work, I programmed a package for Mathematica for Differential Geometry, too. I used two different ways to calculate the Weyl Tensor, but they give different results. One looks like the one OGRe gives, the other is **None Tensor**.

Oh, The metric I used is Robertson-Walker Metric:
$\text{g}_{\mu \nu }(t,r,\theta ,\phi )\text{ = }\left(
\begin{array}{cccc}
 -1 & 0 & 0 & 0 \\
 0 & \frac{a(t)^2}{1-k r^2} & 0 & 0 \\
 0 & 0 & a(t)^2 r^2 & 0 \\
 0 & 0 & 0 & a(t)^2 r^2 \sin ^2(\theta ) \\
\end{array}
\right)$

# Share my work

In the end, I want to share my package with you, which is not as good as yours, but I added something more to my taste.[[Jayce-Ping/SpTm: Space-Time - A Differential Geometry Calculations Package for Wolfram Mathematica. (github.com)](https://github.com/Jayce-Ping/SpTm)](https://github.com/Jayce-Ping/SpTm)

**Comment by bshoshany** [comment]
I have used the package to calculate Weyl tensors before, and did not encounter any problems. Please attach a notebook which includes both the creation of the relevant coordinates and metric and the calculation of the Weyl tensor using `TCalc[]`. I will then be able to determine if you did anything wrong, or if this is a bug in OGRe itself.

**Comment by Jayce-Ping** [comment]
I've never calculate the Weyl Tensor with RW metric before. So I can't figure out which result of three is correct. The latest result I calculate is none Tensor. If you know the exact components of it, please tell me. Thank you~

**Comment by Jayce-Ping** [comment]
I don't know how to upload a wolfram notebook on GitHub. So I sent an email.

**Comment by Jayce-Ping** [comment]
# Previous Mistake
The previous mistake is about input a couple of Chinese parentheses, "（）". The Mathematica would regard it as a symbol. After I correct my mistake, the result is reasonable.

# Solve
And just minites ago, I changed the order of the indices of Riemann Tensor. The calculation result turns to vanish as my program did. And I use another way to check the result. It may be right.

# Result
Because I don't know how to upload a Wolfram Notebook on GitHub, I upload screenshot here:
![image](https://user-images.githubusercontent.com/93087577/218617417-d8b2651d-6867-4bb7-9865-6552be8ee6fa.png)
![image](https://user-images.githubusercontent.com/93087577/218617626-2d65b4ef-4a05-4294-bac9-ed30a867f727.png)
![image](https://user-images.githubusercontent.com/93087577/218617566-dd0756c5-fb2b-47b6-8d54-973d354ffdb3.png)

It's amazing! The Weyl Tensor of a isotropic and homogeneous observer vanishes! It looks like reasonable!

**Comment by bshoshany** [comment]
Great! I'm glad you were able to solve this issue on your own. Please let me know if you have any other issues.

**Comment by bshoshany** [comment]
PS: For future reference, you can attach a notebook to an issue either by putting it in a temporary repository or branch, or by copying the code to [Gist](https://gist.github.com/). Or you can just email it to me.

**Comment by bshoshany** [comment]
I am happy to announce that [OGRe v2.0.0](https://github.com/bshoshany/OGRe/releases/tag/v2.0.0) is now released, and has a new module, `TWeyl[]`, for calculating the Weyl tensor, so you don't need to calculate it manually anymore! Please make sure to update to the latest version; this can be done automatically with `TCheckForUpdates[]`. I would greatly appreciate it if you could pass the news to any colleagues who are using OGRe or might be interested in using it. Please let me know if you have any additional feedback.
